version: "3"
services:

  time:
    image: miknik/repo:1.0
    ports:
      - "3000:3000"
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  frontend:
